language: ruby
rvm:
  - 2.0.0
notifications:
  email:
    on_success: never
    on_failure: never
before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:migrate
