development:
  adapter: mysql2
  host: localhost
  username: root
  password: 
  database: lighthouse_development 

production:
  adapter: mysql2
  host: localhost
  username: root
  password: 
  database: lighthouse_production 

test:
  adapter: mysql2
  adapter: mysql2
  host: localhost
  username: root
  password: 
  database: lighthouse_test
